apiRules:
  - include:
    hasAttribute:
      uidRegex: ^LeagueToolkit\.Meta\.Attributes\.MetaClassAttribute
  - include:
    hasAttribute:
      uidRegex: ^LeagueToolkit\.Meta\.Attributes\.MetaPropertyAttribute
