name: Test Artifact
on: workflow_dispatch

jobs:
  test-artifact:
    env:
      LEAGUE_TOOLKIT_PROJECT: "LeagueToolkit"

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: dir
        run: ls -R ./src/
